### ISSUE TITLE
Every change in tile_buildings2 crash the game

### ISSUE THREAD

**Issue by cybercorpse** [PodeCaradox/Gm1KonverterCrossPlatform#3]
Problem is in a subject. I don't see any log file so I will describe my actions one by one.

1. I've extracted images from tile_buildings2.gm1.
2. I've changed 2 pictures of granary in the "Images" folder on my custom ones.
3. I've imported images and created a new gm1 file.

After all that my game crashes while loading. What have i done wrong? ¯\_(ツ)_/¯

**Comment by PodeCaradox** [comment]
Can you send me you edited picture?

Did you use the orginal Stronghold files, if you have gm1 files edited by imagetoolbox in your GM1 location the maybe wrong and to big and it will crash.(best is to reset all GM1 files and edited new with my tool, because files have issues if they get to big togheter or witb other edited files. 

Send me your edited picture and i test it for you. 

Log files not working right now it will be implement soon.

**Comment by cybercorpse** [comment]
To test the program i have used original Stronghold 1 GM1 file and some building sprites from Stronghold Russian Story. Here's the file:


https://www.upload.ee/files/9980275/tile_buildings2.gm1.html

**Comment by PodeCaradox** [comment]
For me you File works with Stronghold Crusader Extreme, hm i need to check it with Stronghold 1 too, i will test it with Stronghold 1.

Are all files orginal GM1 files from Stronghold 1 or you modified some with Toolbox?

**Comment by cybercorpse** [comment]
> or you modified some with Toolbox?

Nope, I've reinstalled fresh Stronghold especially for modding. :)

**Comment by PodeCaradox** [comment]
Ok i installed now Stronghold 1 and there it wont load the GM1 File(also not the orginal from Stronghold Crusader), but in Stronghold Crusader it works. I will look at the diffrents between the GM1 Files in Stronghold 1 and Stronghold Crusader. Thanks for reporting the issue, i look at the diffrents here so you can also edit Stronghold 1 GM1 Files.

**Comment by cybercorpse** [comment]
OK, thank you. Also, I have made some testing and edited tile_churches.gm1 works just fine for me.

**Comment by PodeCaradox** [comment]
Can you send me the .png files you edit so i can add them and make the GM1 File? I just edit my orginal Stronghold 1 file and that worked? But your not working. 

Maybe the Problem is you need to start the Converter as Administartor and than it will work?

**Comment by cybercorpse** [comment]
Here they are:

https://www.upload.ee/files/9980978/Images.zip.html

I've tried to run the Converter as admin, but it didn't changed anything.

**Comment by PodeCaradox** [comment]
Hey Cybercorpse,

i think i found the issue in my Code, i dont know why but Stronghold 1 want some specific variabels to be set, so i do this now in my Programm(its just a hotfix solution, but works well, i will go in depth later for the issue).  Just Download from the new Release: https://github.com/Gaaammmler/Gm1KonverterCrossPlatform/releases

And one tipp, always start the Programm as Administrator, sometimes it cant overwrite files because of some windows protection, only if the programm started as admin all work as intended.

![img1](https://user-images.githubusercontent.com/5760157/57978141-44414a00-7a07-11e9-999d-64b15074b188.JPG)
